In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
from scipy.stats import linregress
pd.set_option('max_colwidth', 400)

In [2]:
clean_country_df = pd.read_csv('Clean/cleaned_country_data.csv')
clean_country_df.head()

,Country,Hip hop/Rap/R&b,EDM,Pop,Rock/Metal,Latin/Reggaeton,Other,Most Popular Genre
0,australia,31,15,65,17,0,8,Pop
1,canada,39,12,64,14,0,10,Pop
2,china,11,23,108,4,0,21,Pop
3,india,25,1,39,0,0,55,Pop
4,mexico,38,0,18,2,57,43,Latin/Reggaeton

In [3]:
clean_spotify_df = pd.read_csv('Clean/cleaned_spotify_data.csv')
clean_spotify_df.head()

,Title,Artist,Genre,Year,Bpm,Energy,Danceability,dB,Liveness,Valence,Duration (in seconds),Acousticness,Speechiness,Spotify Rating
0,#thatPOWER,will.i.am,Pop,2013,128,61,80,-6,7,40,280,0,6,68
1,(When You Gonna) Give It Up to Me (feat. Keyshia Cole) - Radio Version,Sean Paul,Pop,2006,96,76,71,-3,4,72,244,7,23,68
2,...Baby One More Time,Britney Spears,Pop,1999,93,70,76,-6,44,91,211,20,3,81
3,★,David Bowie,Rock/Metal,2016,98,53,36,-9,18,12,598,21,3,50
4,03' Bonnie & Clyde,JAY-Z,Hip hop/Rap/R&b,2002,90,68,76,-5,15,33,206,23,31,73

In [4]:
song_count = len(clean_spotify_df["Title"].unique())
song_count

2261

In [5]:
artist_count = len(clean_spotify_df["Artist"].unique())
artist_count

1014

In [6]:
genre_count = len(clean_spotify_df["Genre"].unique())
genre_count

6

In [7]:
# mean, median, variance, standard deviation, and SEM of the bpm. 
mean_bpm = clean_spotify_df.groupby(["Genre"]).mean()["Bpm"]
median_bpm = clean_spotify_df.groupby(["Genre"]).median()["Bpm"]
bpm_variance = clean_spotify_df.groupby(["Genre"]).var()["Bpm"]
std_dev_bpm = clean_spotify_df.groupby(["Genre"]).std()["Bpm"]
std_err_bpm = clean_spotify_df.groupby(["Genre"]).sem()["Bpm"]

# Assemble the resulting series into a single summary DataFrame.
bpm_summary = pd.DataFrame({"Mean BPM": mean_bpm,
                             "Median BPM": median_bpm,
                             "BPM Variance": bpm_variance,
                             "BPM Std. Dev.": std_dev_bpm,
                             "BPM Std. Err.": std_err_bpm})

bpm_summary.index.name = None

bpm_summary

,Mean BPM,Median BPM,BPM Variance,BPM Std. Dev.,BPM Std. Err.
EDM,122.646552,125.0,225.656597,15.021871,1.394746
Hip hop/Rap/R&b,117.429078,112.0,945.037590,30.741464,1.294449
Latin/Reggaeton,116.290323,105.0,984.679570,31.379604,5.635943
Other,121.631130,122.0,722.592277,26.881077,1.241253
Pop,119.093113,120.0,678.327244,26.044716,0.811130
Rock/Metal,125.241379,121.5,792.715966,28.155212,2.134441

In [8]:
# mean, median, variance, standard deviation, and SEM of the bpm. 
mean_dur = clean_spotify_df.groupby(["Genre"]).mean()["Duration (in seconds)"]
median_dur = clean_spotify_df.groupby(["Genre"]).median()["Duration (in seconds)"]
dur_variance = clean_spotify_df.groupby(["Genre"]).var()["Duration (in seconds)"]
std_dev_dur = clean_spotify_df.groupby(["Genre"]).std()["Duration (in seconds)"]
std_err_dur = clean_spotify_df.groupby(["Genre"]).sem()["Duration (in seconds)"]

# Assemble the resulting series into a single summary DataFrame.
dur_summary = pd.DataFrame({"Mean Duration": mean_dur,
                             "Median Duration": median_dur,
                             "Duration Variance": dur_variance,
                             "Duration Std. Dev.": std_dev_dur,
                             "Duration Std. Err.": std_err_dur})

dur_summary.index.name = None

dur_summary

,Mean Duration,Median Duration,Duration Variance,Duration Std. Dev.,Duration Std. Err.
EDM,211.931034,208.0,2063.160420,45.422026,4.217329
Hip hop/Rap/R&b,232.918440,231.5,2144.423176,46.307917,1.949915
Latin/Reggaeton,243.096774,242.0,2325.090323,48.219190,8.660422
Other,221.609808,217.0,1434.127339,37.869874,1.748668
Pop,224.548012,220.0,1732.211042,41.619840,1.296197
Rock/Metal,229.614943,224.0,2384.076307,48.827004,3.701566